name: ci

on:
 push:
   branches:
   - main 
    
    
jobs:
   build:
     runs-on: ubuntu-latest
    
     steps:
     - name: checkout-code 
       uses: actions/checkout@v3
           
     - name: print the name 
       run : echo "hello Madhav" 
    
    
